<?php


namespace Control\Form;


use Model\Usuario;
use Pummax\Controller\BaseFormController;
use View\Form\UsuarioForm;

class UsuarioFormController extends BaseFormController
{
    public function createInstanceView()
    {
        return new UsuarioForm();
    }

    protected function addPost()
    {
        $this->beanPost();
        $this->getModel()->setTipo(Usuario::TIPO_ADMIN);
        $this->getEntityManager()->persist($this->getModel());
        $this->getEntityManager()->flush();
    }

    public function createInstanceModel()
    {
        return new Usuario();
    }

    /**
     * @return Usuario
     */
    public function getModel()
    {
        return parent::getModel(); // TODO: Change the autogenerated stub
    }

}