<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Atlética Interno</title>
    <link rel="shortcut icon" href="utils/img/Pummax/favicon.ico<?=$cache?>" />
    <link href="utils/css/bootstrap.min.css<?=$cache?>" rel="stylesheet">
    <link href="utils/css/simple-sidebar.css<?=$cache?>" rel="stylesheet">
    <link href="utils/css/datable.css<?=$cache?>" rel="stylesheet">
    <link href="utils/css/admin.css<?=$cache?>" rel="stylesheet">
    <link href="utils/css/fontawesome.css<?=$cache?>" rel="stylesheet">
    <script src="utils/js/jquery.min.js<?=$cache?>"></script>
    <script src="utils/js/resizable.min.js<?=$cache?>"></script>
    <script src="utils/js/angular.js<?=$cache?>"></script>
    <script src="utils/js/angular-sanitize.js<?=$cache?>"></script>
    <script src="utils/js/jquery.mask.js<?=$cache?>"></script>
    <script src="utils/js/admin-controller.js<?=$cache?>"></script>
    <script src="utils/js/datatable.js<?=$cache?>"></script>
    <script src="utils/js/datatablebootstrap.js<?=$cache?>"></script>
    <script src="utils/js/bootstrap.js<?=$cache?>"></script>
    <script src="utils/js/fontawesome.min.js<?=$cache?>"></script>
    <script src="utils/js/web-app/services/RouterUtil.js<?=$cache?>"></script>
    <script src="utils/js/web-app/MainController.js<?=$cache?>"></script>
    <script src="utils/js/sweetalert.js<?=$cache?>"></script>
</head>
<body ng-app="app">
<div ng-controller="MainController as controller">
    <div id="overlay">
        <div id="text">Processando&nbsp;<i class="fas fa-spinner fa-spin"></i></div>
    </div>
    <div class="d-flex" id="wrapper">
        <div class="bg-light border-right" id="sidebar-wrapper">
            <div class="logo-menu">
                <img class="center" src="/utils/img/logo.png">
            </div>
            <div class="sidebar-heading">&nbsp;</div>
            <div class="list-group list-group-flush">
                <?php foreach (\Pummax\Configuration\MenuDefine::getAllMenus() as $menuName => $menu){ ?>
                    <button ng-click="controller.selectMenu('<?= $menu['router'] ?>')" class="list-group-item list-group-item-action bg-light"><i class="<?= $menu['icon'] ?>"></i>&nbsp;<?= $menuName ?></button>
                <?php } ?>
            </div>
        </div>
        <div id="page-content-wrapper">
            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                <button class="btn btn-light" id="menu-toggle"><i class="far fa-window-close"></i></button>
                <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
                </form>
                <ul class="navbar-nav ml-auto ml-md-0">
                    <?= $data->format('d/m/Y H:i')?>
                    <li class="nav-item dropdown">
                        <a style="color: white" class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="far fa-user"></i>&nbsp;<?= $usuario ?></a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                            <a class="dropdown-item" href="/"><i class="fas fa-step-backward"></i>&nbsp;Pagina Inicial<span class="sr-only">(current)</span></a>
                            <a class="dropdown-item" href="/logout"><i class="fas fa-sign-out-alt"></i>&nbsp;Sair<span class="sr-only">(current)</span></a>
                        </div>
                    </li>
                </ul>
            </nav>
            <?php include 'form-template.phtml';?>
            <div id="append" class="container-fluid">
                <?= $mensagemErro ?>
                <?= $mensagemSuccess ?>
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                    <li ng-repeat="tab in tabs" class="nav-item">
                        <a ng-mousedown="controller.clickTab(tab, $event)" class="nav-link" id="{{tab.router}}-tab" data-toggle="tab" href="#{{tab.router}}" role="tab" aria-controls="{{tab.router}}" aria-selected="true">
                            <span>{{tab.title}}&nbsp;<i ng-click="controller.closeTab(tab.router)" class="far fa-times-circle"></i></span>
                        </a>
                    </li>
                </ul>
                <div class="tab-content" id="myTabContent">
                    <div ng-repeat="tab in tabs" class="tab-pane fade" id="{{tab.router}}" role="tabpanel" aria-labelledby="{{tab.router}}-tab">
                        <div class="append-in-tab">
                            <?php include 'grid-template.phtml';?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $("#menu-toggle").click(function (e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    $(document).ready(function() {
        closeMessages(5000);
    });
</script>
</body>
</html>