<style>
    .color-base{
        background-color: rgb(255, 124, 0) !important;
    }
    a{
        color: white;
    }
    a:hover{
        color: white;
    }
</style>
<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top color-base">
        <a class="navbar-brand" href="/index">
            <img style="border-radius: 100px!important; width: 40px;" src="/utils/img/logo2.jpg"> Atlética CEAVI
        </a>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbarCollapse" style="">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/index">
                        <i class="fas fa-home"></i>&nbsp;Ínicio
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/about">
                        <i class="fas fa-building"></i>&nbsp;Como Funciona
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/login">
                        <i class="fas fa-sign-in-alt"></i>&nbsp;Login
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
            </ul>
        </div>
    </nav>
</header>