<style>
    .color-base{
        background-color: rgb(255, 124, 0) !important;
    }
    a{
        color: white;
    }
    a:hover{
        color: white;
    }
</style>
<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top color-base">
        <a class="navbar-brand" href="/index">
            <img style="border-radius: 100px!important; width: 40px;" src="/utils/img/logo2.jpg"> <?= \Pummax\Configuration\DataBase::NOME_SISTEMA ?>
        </a>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbarCollapse" style="">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/index">
                        <i class="fas fa-home"></i>&nbsp;Ínicio
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/about">
                        <i class="fas fa-building"></i>&nbsp;Como Funciona
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <?php if(!$usuario) { ?>
                    <li class="nav-item active">
                        <a class="nav-link" href="/login">
                            <i class="fas fa-sign-in-alt"></i>&nbsp;Login
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                <?php }else{ ?>
                    <li class="nav-item active dropdown">
                        <a style="color: white" class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="far fa-user-circle"></i>&nbsp;<?= $usuario ?></a>
                        <div class="dropdown-menu" aria-labelledby="userDropdown">
                            <a class="dropdown-item" href="/profile"><i class="far fa-id-badge"></i>&nbsp;Meu Perfil<span class="sr-only">(current)</span></a>
                            <a class="dropdown-item" href="/carterinha"><i class="far fa-id-card"></i>&nbsp;Carteirinha<span class="sr-only">(current)</span></a>
                        </div>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/logout">
                            <i class="fas fa-sign-out-alt"></i>&nbsp;Sair
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                <?php } ?>
            </ul>
        </div>
    </nav>
</header>